version: "3.9"
services:
  postgres:
    image: postgres:15.2
    environment:
      POSTGRES_DB: "market_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"