spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/market_db
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        show_sql: true
        ddl-auto: create-drop
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
server:
  port: 8080